### PR TITLE
feat: support chaining

### PR DESCRIPTION
**Pull request by TPORL**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

```javascript
const subRouter = app.router.namespace('/sub');

subRouter
  .get('/a', app.controller.sub.a)
  .get('/b', app.controller.sub.b)
```

### CODE REVIEW

**Comment by atian25** [comment]
需要加对应的测试用例

**Review by atian25 — COMMENTED** [review]
不是要测试 controller.a.b.c 么

**Comment by TPORL** [comment]
是namespace返回的对象的可以链式调用
只要各个方法返回的对象和namespace返回对象是同一个就可以了吧？

**Comment by atian25** [comment]
测试用例一般要用真实的用法

**Comment by atian25** [comment]
单测挂了，需要修复下

**Review by atian25 — APPROVED** [review]

**Comment by atian25** [comment]
land 1.3.0, thanks for your works

**Pull request merged**
